//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Daisy.SaveAsDAISY {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RibbonLabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RibbonLabels() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Daisy.SaveAsDAISY.Ribbon.Labels.RibbonLabels", typeof(RibbonLabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Abbreviations.
        /// </summary>
        public static string AbbreviationsGroup {
            get {
                return ResourceManager.GetString("AbbreviationsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Acronyms.
        /// </summary>
        public static string AcronymsGroup {
            get {
                return ResourceManager.GetString("AcronymsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add &amp;footnotes.
        /// </summary>
        public static string AddFootnotesTabButton {
            get {
                return ResourceManager.GetString("AddFootnotesTabButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DAISY Styles.
        /// </summary>
        public static string DaisyStylesGroup {
            get {
                return ResourceManager.GetString("DaisyStylesGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Documentation.
        /// </summary>
        public static string DocumentationTabMenu {
            get {
                return ResourceManager.GetString("DocumentationTabMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Language.
        /// </summary>
        public static string DocumentLanguageTabButton {
            get {
                return ResourceManager.GetString("DocumentLanguageTabButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export.
        /// </summary>
        public static string ExportGroup {
            get {
                return ResourceManager.GetString("ExportGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à S&amp;ave as DAISY.
        /// </summary>
        public static string ExportTabMenu {
            get {
                return ResourceManager.GetString("ExportTabMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;DAISY3.
        /// </summary>
        public static string ExportToDaisy3OfficeButton {
            get {
                return ResourceManager.GetString("ExportToDaisy3OfficeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;DAISY3.
        /// </summary>
        public static string ExportToDaisy3TabButton {
            get {
                return ResourceManager.GetString("ExportToDaisy3TabButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;EPUB3 (experimental).
        /// </summary>
        public static string ExportToEpub3OfficeButton {
            get {
                return ResourceManager.GetString("ExportToEpub3OfficeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;EPUB3 (experimental).
        /// </summary>
        public static string ExportToEpub3TabButton {
            get {
                return ResourceManager.GetString("ExportToEpub3TabButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DAISY &amp;XML.
        /// </summary>
        public static string ExportToXMLOfficeButton {
            get {
                return ResourceManager.GetString("ExportToXMLOfficeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DAISY &amp;XML.
        /// </summary>
        public static string ExportToXMLTabButton {
            get {
                return ResourceManager.GetString("ExportToXMLTabButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Footnotes.
        /// </summary>
        public static string FootnotesGroup {
            get {
                return ResourceManager.GetString("FootnotesGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Help.
        /// </summary>
        public static string HelpGroup {
            get {
                return ResourceManager.GetString("HelpGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Import.
        /// </summary>
        public static string ImportDaisyStylesTabButton {
            get {
                return ResourceManager.GetString("ImportDaisyStylesTabButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language.
        /// </summary>
        public static string LanguageGroup {
            get {
                return ResourceManager.GetString("LanguageGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ma&amp;nage abbreviations.
        /// </summary>
        public static string ManageAbbreviationsTabButton {
            get {
                return ResourceManager.GetString("ManageAbbreviationsTabButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mana&amp;ge acronyms.
        /// </summary>
        public static string ManageAcronymsTabButton {
            get {
                return ResourceManager.GetString("ManageAcronymsTabButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mark as a&amp;bbreviation.
        /// </summary>
        public static string MarkAbbreviationTabButton {
            get {
                return ResourceManager.GetString("MarkAbbreviationTabButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mark as a&amp;cronym.
        /// </summary>
        public static string MarkAcronymTabButton {
            get {
                return ResourceManager.GetString("MarkAcronymTabButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Authoring guidelines.
        /// </summary>
        public static string OpenGuidelinesTabButton {
            get {
                return ResourceManager.GetString("OpenGuidelinesTabButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Instruction manual.
        /// </summary>
        public static string OpenManualTabButton {
            get {
                return ResourceManager.GetString("OpenManualTabButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save As DAIS&amp;Y.
        /// </summary>
        public static string SaveAsDaisyOfficeMenu {
            get {
                return ResourceManager.GetString("SaveAsDaisyOfficeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accessibility.
        /// </summary>
        public static string SaveAsDAISYTab {
            get {
                return ResourceManager.GetString("SaveAsDAISYTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        public static string SettingsGroup {
            get {
                return ResourceManager.GetString("SettingsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Settings.
        /// </summary>
        public static string SettingsTabButton {
            get {
                return ResourceManager.GetString("SettingsTabButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validate.
        /// </summary>
        public static string toggleValidateTabButton {
            get {
                return ResourceManager.GetString("toggleValidateTabButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validation.
        /// </summary>
        public static string ValidateGroup {
            get {
                return ResourceManager.GetString("ValidateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Version details.
        /// </summary>
        public static string VersionDetailsTabButton {
            get {
                return ResourceManager.GetString("VersionDetailsTabButton", resourceCulture);
            }
        }
    }
}
