// DaisyWord2007Shim.idl 
import "oaidl.idl";
import "ocidl.idl";

[
	uuid(9D557660-3334-4368-B01F-201447264E9A),
	version(1.0),
	helpstring("DaisyWord2007Shim 1.0 Type Library")
]
library DaisyWord2007ShimLib
{
	importlib("stdole2.tlb");

	[
		uuid(18cbc6a8-bcb5-45ed-8ff3-655599e1f872),
		helpstring("ConnectProxy Class")
	]
	coclass ConnectProxy
	{
		[default] interface IUnknown;
	};

};
















