// DaisyTranslatorWord2003Shim.idl 
import "oaidl.idl";
import "ocidl.idl";

[
	uuid(3D3294A1-C5BF-4D26-B150-E7175447B5BB),
	version(1.0),
	helpstring("DaisyTranslatorWord2003Shim 1.0 Type Library")
]
library DaisyTranslatorWord2003ShimLib
{
	importlib("stdole2.tlb");

	[
		uuid(32b42a31-8592-459f-b6ae-ac70d254cd14),
		helpstring("ConnectProxy Class")
	]
	coclass ConnectProxy
	{
		[default] interface IUnknown;
	};

};
















