//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Daisy.SaveAsDAISY {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Daisy.SaveAsDAISY.Messages.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Selected text is already marked as Abbreviation..
        /// </summary>
        public static string AbbreviationAlready {
            get {
                return ResourceManager.GetString("AbbreviationAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Selected text is not valid for marking as an Abbreviation. Please select a word.
        /// </summary>
        public static string AbbreviationproperText {
            get {
                return ResourceManager.GetString("AbbreviationproperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please select a word to mark as Abbreviation.
        /// </summary>
        public static string AbbreviationText {
            get {
                return ResourceManager.GetString("AbbreviationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Selected text is already marked as Acronym..
        /// </summary>
        public static string AcronymAlready {
            get {
                return ResourceManager.GetString("AcronymAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want the reader to pronounce the acronym? .
        /// </summary>
        public static string AcronymConfirmation {
            get {
                return ResourceManager.GetString("AcronymConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Selected text is not valid for marking as an Acronym. Please select a word.
        /// </summary>
        public static string AcronymproperText {
            get {
                return ResourceManager.GetString("AcronymproperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please select text to mark as Acronym.
        /// </summary>
        public static string AcronymText {
            get {
                return ResourceManager.GetString("AcronymText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Some of the added documents are MasterSub documents.Please add simple documents..
        /// </summary>
        public static string AddSimpleMasterSub {
            get {
                return ResourceManager.GetString("AddSimpleMasterSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to apply for all occurences of this word?.
        /// </summary>
        public static string AllOccurences {
            get {
                return ResourceManager.GetString("AllOccurences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select the destination folder.
        /// </summary>
        public static string ChoseDestination {
            get {
                return ResourceManager.GetString("ChoseDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please select the output file.
        /// </summary>
        public static string ChoseDestinationFile {
            get {
                return ResourceManager.GetString("ChoseDestinationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please select the Destination Folder.
        /// </summary>
        public static string DaisyOutput_Folder {
            get {
                return ResourceManager.GetString("DaisyOutput Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please save the document before Translating to DAISY.
        /// </summary>
        public static string DaisySaveDocumentBeforeExport {
            get {
                return ResourceManager.GetString("DaisySaveDocumentBeforeExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please save the document before updating the Language details.
        /// </summary>
        public static string DaisySaveDocumentBeforelanguage {
            get {
                return ResourceManager.GetString("DaisySaveDocumentBeforelanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please save the document before Validating.
        /// </summary>
        public static string DaisySaveDocumentBeforeValidate {
            get {
                return ResourceManager.GetString("DaisySaveDocumentBeforeValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please save the document in word2007 format.
        /// </summary>
        public static string DaisySaveDocumentin2007 {
            get {
                return ResourceManager.GetString("DaisySaveDocumentin2007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An unexpected error occured. Please feel free to fill a bug report on the project web site (https://www.github.com/daisy/word-save-as-daisy/) with your file attached..
        /// </summary>
        public static string DaisyUnexpectedError {
            get {
                return ResourceManager.GetString("DaisyUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select the destination folder .
        /// </summary>
        public static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter a title..
        /// </summary>
        public static string EnterTitle {
            get {
                return ResourceManager.GetString("EnterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Translation failed, and translated document is invalid..
        /// </summary>
        public static string FailedLabel {
            get {
                return ResourceManager.GetString("FailedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The following elements are lost during translation..
        /// </summary>
        public static string FeedbackLabel {
            get {
                return ResourceManager.GetString("FeedbackLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please save the document before managing abbreviations.
        /// </summary>
        public static string ManageSaveDocumentAbbr {
            get {
                return ResourceManager.GetString("ManageSaveDocumentAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please save the document before managing acronyms.
        /// </summary>
        public static string ManageSaveDocumentAcr {
            get {
                return ResourceManager.GetString("ManageSaveDocumentAcr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please save the document before marking abbreviation.
        /// </summary>
        public static string MarkSaveDocumentAbbr {
            get {
                return ResourceManager.GetString("MarkSaveDocumentAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please save the document before marking acronym.
        /// </summary>
        public static string MarkSaveDocumentAcr {
            get {
                return ResourceManager.GetString("MarkSaveDocumentAcr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to translate the current document along with sub documents?.
        /// </summary>
        public static string MasterSubConfirmation {
            get {
                return ResourceManager.GetString("MasterSubConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Following documents are opened. Please close the following documents before translation:.
        /// </summary>
        public static string OPenState {
            get {
                return ResourceManager.GetString("OPenState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Some Sub documents are in open state. Please close all the Sub documents before Translation:.
        /// </summary>
        public static string OpenSubOwn {
            get {
                return ResourceManager.GetString("OpenSubOwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please close the selected document and click on &quot;Update&quot; button. .
        /// </summary>
        public static string Populateopen {
            get {
                return ResourceManager.GetString("Populateopen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to cancel the translation?.
        /// </summary>
        public static string QuitConfirmation {
            get {
                return ResourceManager.GetString("QuitConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Successfully Translated the document. .
        /// </summary>
        public static string SucessLabel {
            get {
                return ResourceManager.GetString("SucessLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Track changes is set for this document.Do you want to accept all changes? .
        /// </summary>
        public static string TrackConfirmation {
            get {
                return ResourceManager.GetString("TrackConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validation error found while translating the following documents.
        ///.
        /// </summary>
        public static string WellDaisyFormat {
            get {
                return ResourceManager.GetString("WellDaisyFormat", resourceCulture);
            }
        }
    }
}
