//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Daisy.SaveAsDAISY.Forms.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Daisy.SaveAsDAISY.Forms.Properties.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Selected text is already marked as Abbreviation..
        /// </summary>
        internal static string AbbreviationAlready {
            get {
                return ResourceManager.GetString("AbbreviationAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Selected text is not valid for marking as an Abbreviation. Please select a word.
        /// </summary>
        internal static string AbbreviationproperText {
            get {
                return ResourceManager.GetString("AbbreviationproperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please select a word to mark as Abbreviation.
        /// </summary>
        internal static string AbbreviationText {
            get {
                return ResourceManager.GetString("AbbreviationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Selected text is already marked as Acronym..
        /// </summary>
        internal static string AcronymAlready {
            get {
                return ResourceManager.GetString("AcronymAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want the reader to pronounce the acronym? .
        /// </summary>
        internal static string AcronymConfirmation {
            get {
                return ResourceManager.GetString("AcronymConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Selected text is not valid for marking as an Acronym. Please select a word.
        /// </summary>
        internal static string AcronymproperText {
            get {
                return ResourceManager.GetString("AcronymproperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please select text to mark as Acronym.
        /// </summary>
        internal static string AcronymText {
            get {
                return ResourceManager.GetString("AcronymText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Some of the added documents are MasterSub documents.Please add simple documents..
        /// </summary>
        internal static string AddSimpleMasterSub {
            get {
                return ResourceManager.GetString("AddSimpleMasterSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to apply for all occurences of this word?.
        /// </summary>
        internal static string AllOccurences {
            get {
                return ResourceManager.GetString("AllOccurences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Images.
        /// </summary>
        internal static string Caption_above_the_Image_is_not_translated {
            get {
                return ResourceManager.GetString("Caption above the Image is not translated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tables.
        /// </summary>
        internal static string Caption_below_the_Table_is_not_translated {
            get {
                return ResourceManager.GetString("Caption below the Table is not translated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select the destination folder.
        /// </summary>
        internal static string ChoseDestination {
            get {
                return ResourceManager.GetString("ChoseDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please select the output file.
        /// </summary>
        internal static string ChoseDestinationFile {
            get {
                return ResourceManager.GetString("ChoseDestinationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Track Changes.
        /// </summary>
        internal static string Comment_Reference_is_not_translated {
            get {
                return ResourceManager.GetString("Comment Reference is not translated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Full D&amp;AISY (from single docx).
        /// </summary>
        internal static string DaisyDtbook {
            get {
                return ResourceManager.GetString("DaisyDtbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save As DAIS&amp;Y.
        /// </summary>
        internal static string DaisyImportLabel {
            get {
                return ResourceManager.GetString("DaisyImportLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DAISY XML (from &amp;Multiple docx).
        /// </summary>
        internal static string DaisyMultiple {
            get {
                return ResourceManager.GetString("DaisyMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à F&amp;ull DAISY (from Multiple docx).
        /// </summary>
        internal static string DaisyMultipleDtbook {
            get {
                return ResourceManager.GetString("DaisyMultipleDtbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please select the Destination Folder.
        /// </summary>
        internal static string DaisyOutput_Folder {
            get {
                return ResourceManager.GetString("DaisyOutput Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saves this file in DAISY Format.
        /// </summary>
        internal static string DaisySaveASDescription {
            get {
                return ResourceManager.GetString("DaisySaveASDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save As DAISY.
        /// </summary>
        internal static string DaisySaveASLabel {
            get {
                return ResourceManager.GetString("DaisySaveASLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please save the document before Translating to DAISY.
        /// </summary>
        internal static string DaisySaveDocumentBeforeExport {
            get {
                return ResourceManager.GetString("DaisySaveDocumentBeforeExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please save the document before updating the Language details.
        /// </summary>
        internal static string DaisySaveDocumentBeforelanguage {
            get {
                return ResourceManager.GetString("DaisySaveDocumentBeforelanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please save the document before Validating.
        /// </summary>
        internal static string DaisySaveDocumentBeforeValidate {
            get {
                return ResourceManager.GetString("DaisySaveDocumentBeforeValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please save the document in word2007 format.
        /// </summary>
        internal static string DaisySaveDocumentin2007 {
            get {
                return ResourceManager.GetString("DaisySaveDocumentin2007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DAISY XML (from &amp;Single docx).
        /// </summary>
        internal static string DaisySingle {
            get {
                return ResourceManager.GetString("DaisySingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An unexpected error occured. Please feel free to fill a bug report on the project web site (http://openxml-daisy.sourceforge.net) with your file attached..
        /// </summary>
        internal static string DaisyUnexpectedError {
            get {
                return ResourceManager.GetString("DaisyUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Full D&amp;AISY (from single docx).
        /// </summary>
        internal static string DaisyXml {
            get {
                return ResourceManager.GetString("DaisyXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select the destination folder .
        /// </summary>
        internal static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SaveAsDAISY - Error Message.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Images.
        /// </summary>
        internal static string External_Images_are_not_translated {
            get {
                return ResourceManager.GetString("External Images are not translated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Translation failed, and translated document is invalid..
        /// </summary>
        internal static string FailedLabel {
            get {
                return ResourceManager.GetString("FailedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The following elements are lost during translation..
        /// </summary>
        internal static string FeedbackLabel {
            get {
                return ResourceManager.GetString("FeedbackLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Full form of Abbreviation:.
        /// </summary>
        internal static string FullAbbr {
            get {
                return ResourceManager.GetString("FullAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Full form of Acronym:.
        /// </summary>
        internal static string FullAcr {
            get {
                return ResourceManager.GetString("FullAcr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Images.
        /// </summary>
        internal static string Geometric_shapes_are_not_translated {
            get {
                return ResourceManager.GetString("Geometric shapes are not translated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Images.
        /// </summary>
        internal static string Image_is_Corrupted {
            get {
                return ResourceManager.GetString("Image is Corrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SaveAsDAISY - Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Translated document is invalid..
        /// </summary>
        internal static string InvalidMaster {
            get {
                return ResourceManager.GetString("InvalidMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please save the document before managing abbreviations.
        /// </summary>
        internal static string ManageSaveDocumentAbbr {
            get {
                return ResourceManager.GetString("ManageSaveDocumentAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please save the document before managing acronyms.
        /// </summary>
        internal static string ManageSaveDocumentAcr {
            get {
                return ResourceManager.GetString("ManageSaveDocumentAcr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mark Abbreviation.
        /// </summary>
        internal static string MarkAbbr {
            get {
                return ResourceManager.GetString("MarkAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manage Acronym.
        /// </summary>
        internal static string MarkAcr {
            get {
                return ResourceManager.GetString("MarkAcr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please save the document before marking abbreviation.
        /// </summary>
        internal static string MarkSaveDocumentAbbr {
            get {
                return ResourceManager.GetString("MarkSaveDocumentAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please save the document before marking acronym.
        /// </summary>
        internal static string MarkSaveDocumentAcr {
            get {
                return ResourceManager.GetString("MarkSaveDocumentAcr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to translate the current document along with sub documents?.
        /// </summary>
        internal static string MasterSubConfirmation {
            get {
                return ResourceManager.GetString("MasterSubConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot mark up for this text.
        /// </summary>
        internal static string NullAbbrException {
            get {
                return ResourceManager.GetString("NullAbbrException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Images.
        /// </summary>
        internal static string Object_is_not_translated {
            get {
                return ResourceManager.GetString("Object is not translated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Following documents are opened. Please close the following documents before translation:.
        /// </summary>
        internal static string OPenState {
            get {
                return ResourceManager.GetString("OPenState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Some Sub documents are in open state. Please close all the Sub documents before Translation:.
        /// </summary>
        internal static string OpenSubOwn {
            get {
                return ResourceManager.GetString("OpenSubOwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please close the selected document and click on &quot;Update&quot; button. .
        /// </summary>
        internal static string Populateopen {
            get {
                return ResourceManager.GetString("Populateopen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Some Problem in Sub documents.
        /// </summary>
        internal static string ProblemMasterSub {
            get {
                return ResourceManager.GetString("ProblemMasterSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Some problem occured in the data of .
        /// </summary>
        internal static string ProblemOccur {
            get {
                return ResourceManager.GetString("ProblemOccur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to cancel the translation?.
        /// </summary>
        internal static string QuitConfirmation {
            get {
                return ResourceManager.GetString("QuitConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Images.
        /// </summary>
        internal static string Shapes_are_not_translated {
            get {
                return ResourceManager.GetString("Shapes are not translated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please select documents.
        /// </summary>
        internal static string SubdocsError {
            get {
                return ResourceManager.GetString("SubdocsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Successfully Translated the document. .
        /// </summary>
        internal static string SucessLabel {
            get {
                return ResourceManager.GetString("SucessLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter the Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OOXML.
        /// </summary>
        internal static string TOC_is_not_translated {
            get {
                return ResourceManager.GetString("TOC is not translated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Track changes is set for this document.Do you want to accept all changes? .
        /// </summary>
        internal static string TrackConfirmation {
            get {
                return ResourceManager.GetString("TrackConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Comment Reference is not translated.
        /// </summary>
        internal static string translation_oox2Daisy_commentReference {
            get {
                return ResourceManager.GetString("translation.oox2Daisy.commentReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à External Images are not translated.
        /// </summary>
        internal static string translation_oox2Daisy_ExternalImage {
            get {
                return ResourceManager.GetString("translation.oox2Daisy.ExternalImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Geometric shapes are not translated.
        /// </summary>
        internal static string translation_oox2Daisy_GeometricShapeElement {
            get {
                return ResourceManager.GetString("translation.oox2Daisy.GeometricShapeElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Images are not translated.
        /// </summary>
        internal static string translation_oox2Daisy_Image {
            get {
                return ResourceManager.GetString("translation.oox2Daisy.Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Caption above the Image is not translated.
        /// </summary>
        internal static string translation_oox2Daisy_ImageCaption {
            get {
                return ResourceManager.GetString("translation.oox2Daisy.ImageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Image is Corrupted.
        /// </summary>
        internal static string translation_oox2Daisy_ImageContent {
            get {
                return ResourceManager.GetString("translation.oox2Daisy.ImageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Object is not translated.
        /// </summary>
        internal static string translation_oox2Daisy_object {
            get {
                return ResourceManager.GetString("translation.oox2Daisy.object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  is not translated.
        /// </summary>
        internal static string translation_oox2Daisy_sdtElement {
            get {
                return ResourceManager.GetString("translation.oox2Daisy.sdtElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Shapes are not translated.
        /// </summary>
        internal static string translation_oox2Daisy_shapeElement {
            get {
                return ResourceManager.GetString("translation.oox2Daisy.shapeElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Caption below the Table is not translated.
        /// </summary>
        internal static string translation_oox2Daisy_TableCaption {
            get {
                return ResourceManager.GetString("translation.oox2Daisy.TableCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  is not translated.
        /// </summary>
        internal static string translation_oox2Daisy_UncoveredElement {
            get {
                return ResourceManager.GetString("translation.oox2Daisy.UncoveredElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Translation failed..
        /// </summary>
        internal static string TranslationFailed {
            get {
                return ResourceManager.GetString("TranslationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to create target file.
        /// </summary>
        internal static string UnableToCreateOutputLabel {
            get {
                return ResourceManager.GetString("UnableToCreateOutputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validation error found while translating the following documents.
        ///.
        /// </summary>
        internal static string WellDaisyFormat {
            get {
                return ResourceManager.GetString("WellDaisyFormat", resourceCulture);
            }
        }
    }
}
