# Host part of webservice address
# Leave empty if you wish to use the app_path setting
host: http://localhost

# Port part of webservice address
# Leave empty if you wish to use the app_path setting
port: 8181

# Path part of webservice address, as in HOST:PORT/PATH (e.g. http://localhost:8181/ws)
# Leave empty if you wish to use the app_path setting
ws_path: ws

# Timeout for requests to the webservice in seconds
timeout: 10

# Path to webservice launch script
exec_line: ../bin/pipeline2.bat

# Client key for authenticated requests
#client_key: clientid

# Client secrect for authenticated requests
#client_secret: supersecret

# Print debug messages
debug: false

# Start the DAISY Pipeline app if it is not running
starting: true
