// DaisyTranslatorWordXPShim.idl 
import "oaidl.idl";
import "ocidl.idl";

[
	uuid(31EC2B7C-43AE-4716-BBF7-2D02A74047CD),
	version(1.0),
	helpstring("DaisyTranslatorWordXPShim 1.0 Type Library")
]
library DaisyTranslatorWordXPShimLib
{
	importlib("stdole2.tlb");

	[
		uuid(c16065a7-4a10-490e-8d8a-5c807ff31434),
		helpstring("ConnectProxy Class")
	]
	coclass ConnectProxy
	{
		[default] interface IUnknown;
	};

};
















